name: team_up_nc
description: "Team Up NC - A modern event notifications app with beautiful card designs and no-login notifications"
publish_to: "none"
version: 1.0.1+4

environment:
  sdk: ^3.6.0

dependencies:
  flutter:
    sdk: flutter
  add_2_calendar: any
  cupertino_icons: any
  google_fonts: any
  http: any
  shared_preferences: any
  flutter_local_notifications: any
  cached_network_image: any
  intl: any
  url_launcher: any
  firebase_core: any
  firebase_remote_config: any
  firebase_messaging: any
  timezone: any
  flutter_app_badger: any

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true
  
  assets:
    - assets/images/
